---
title: "Data Preparation"
output: html_document
author: "Team HafenJungs"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
	fig.height = 10,
	fig.width = 12,
	message = FALSE,
	warning = FALSE,
	echo = FALSE,
	results = "asis"
	)
```


## Look at the data

```{r}
library(tidyverse)
library(lubridate)
library(modelr)
library(dplyr)

in_path <- "../input/"
out_path <- "../output/"

nettebad_test <- read_csv(paste0(in_path, "nettebad_test_set.csv"))
nettebad_train <- read_csv(paste0(in_path, "nettebad_train_set.csv"))
weather_dwd_test <- read_csv(paste0(in_path, "weather_dwd_test_set.csv"))
weather_dwd_train <- read_csv(paste0(in_path, "weather_dwd_train_set.csv"))
weather_uni_osnabrueck_test <- read_csv(paste0(in_path, "weather_uni_osnabrueck_test_set.csv"))
weather_uni_osnabrueck_train <- read_csv(paste0(in_path, "weather_uni_osnabrueck_train_set.csv"))
sample_submission_nettebad <- read_csv(paste0(in_path, "sample_submission_nettebad.csv"))

```


## Prepare Data

```{r}
nettebad_train <- nettebad_train %>%
  mutate(date = mdy(date)) %>%
  mutate(yr = year(date),
         month = month(date),
         day = day(date))

nettebad_test <- nettebad_test %>%
  mutate(date = mdy(date)) %>%
  mutate(yr = year(date),
         month = month(date),
         day = day(date))


weather_dwd_train <- weather_dwd_train %>%
  mutate(date = mdy(date)) %>%
  mutate(yr = year(date),
         month = month(date),
         day = day(date))

weather_dwd_test <- weather_dwd_test %>%
  mutate(date = mdy(date)) %>%
  mutate(yr = year(date),
         month = month(date),
         day = day(date))

weather_uni_osnabrueck_test <- weather_uni_osnabrueck_test %>%
  mutate(date = mdy(date)) %>%
  mutate(yr = year(date),
         month = month(date),
         day = day(date))

test_set <- left_join(nettebad_test,weather_uni_osnabrueck_test) %>%
  left_join(.,weather_dwd_test)

train_set <- left_join(nettebad_train,weather_uni_osnabrueck_train) %>%
  left_join(.,weather_dwd_train)

```



## Visualize Data: Visitors per day plots

```{r}
ggplot(train_set, aes(y = visitors_pool_total, x = date)) +
  geom_point() + theme_bw() + facet_wrap(~ yr, scales = "free") +
  geom_smooth()
```

## Make Predictions


### Mean

```{r}
hafen_submission_mean_visitors <- sample_submission_nettebad %>%
  mutate(visitors_pool_total = mean(nettebad_train$visitors_pool_total))
```

```{r}
write_csv(hafen_submission_mean_visitors, path = paste0(out_path,"hafen_submission_mean_visitors",".csv"))

write_csv(test_set, path = paste0(in_path,"test_set",".csv"))
write_csv(train_set, path = paste0(in_path,"train_set",".csv"))
```
